project_root: /home/vagrant/test
project_dir: test
project_name: dj
git_repo: https://github.com/Ins1ne/test.git
git_rev: master
virtualenv: /home/vagrant/venv
user: vagrant
web_user: vagrant
web_group: vagrant
db_master: origin_db
db_slave: satellite_defaul
group: django
media: media
