project_root: /home/vagrant/satellite-simplified
project_dir: satellite-simplified
project_name: satellites_simplified
virtualenv: /home/vagrant/env
user: vagrant
web_user: vagrant
web_group: vagrant
db_master: origin_db
db_slave: satellite_default
media_proxy: https://s.gamestand.org/media/
